version: "3.8"
services:
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_c
    image: dpage/pgadmin4:5.5
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  back:
    depends_on:
      - db
    build:
      context: ./aeroporto-ban2-server
    volumes:
      - .:/aeroporto-ban2-server
    ports:
      - "5000:5000"
  front:
    depends_on:
      - back
    build:
      context: ./aeroporto-ban2-web
    volumes:
      - .:/aeroporto-ban2-web
    ports:
      - "5173:5173"
volumes:
  db-data:
  pgadmin-data:
