version: "3.8"
services:
  back:
    build:
      context: ./aeroporto-ban2-server
    volumes:
      - .:/aeroporto-ban2-server
    ports:
      - "5000:5000"
  front:
    depends_on:
      - back
    build:
      context: ./aeroporto-ban2-web
    volumes:
      - .:/aeroporto-ban2-web
    ports:
      - "5173:5173"
